name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  branch-naming:
    name: Validate branch name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          BRANCH="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH"

          # Must start with a valid prefix
          if [[ ! "$BRANCH" =~ ^(feature|bugfix|hotfix|chore|docs|refactor|test)/ ]]; then
            echo "::error::Branch name must start with a valid prefix (feature/, bugfix/, hotfix/, chore/, docs/, refactor/, test/)"
            exit 1
          fi

          # After prefix, must be lowercase kebab-case
          SUFFIX="${BRANCH#*/}"
          if [[ ! "$SUFFIX" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
            echo "::error::Branch name after prefix must be lowercase kebab-case (e.g., feature/my-new-feature)"
            exit 1
          fi

          echo "Branch name is valid."

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check formatting
        run: lune run ./Submodules/luau-cicd/Scripts/CheckFormatting.luau

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install dependencies
        run: wally install

      - name: Run tests
        run: lune run ./Scripts/RunTests.luau

  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install dependencies
        run: wally install

      - name: Setup Lune typedefs
        run: lune setup --no-update-luaurc

      - name: Run static analysis
        run: lune run ./Submodules/luau-cicd/Scripts/RunStaticAnalysis.luau

  version-match:
    name: Check version match
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check version match
        run: lune run ./Submodules/luau-cicd/Scripts/CheckVersionMatch.luau
